### ISSUE TITLE
Performance of this SSD+FPN on any dataset?

### ISSUE THREAD

**Issue by qilicun** [zunzhumu/ssd#1]
Hi,
I see that you combine FPN with SSD, so I'm wondering how the performance of this changes on VOC2007 & VOC2012? Thanks

**Comment by zunzhumu** [comment]
@qilicun 会有点提升在VOC上面，但是提升不大，我的目标不是为了做FPN而是准备写一些其他operater做尝试

**Comment by qilicun** [comment]
@zunzhumu 好的，非常感谢
